variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_linux:
  stage: build
  script:
    - ./bootstrap.sh
    - ./configure --with-sdkdir=$HOME/pure-data/src --enable-cmem
    - make
  artifacts:
    paths:
      - $CI_PROJECT_DIR/tutorial/*.pd_linux

test_linux:
  stage: test
  script:
    - $CI_PROJECT_DIR/tutorial/pd/test.sh $CI_PROJECT_DIR

push_github:
    stage: deploy
    script:
        - git remote add github https://$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$CI_PROJECT_NAME.git || true
        # we need some extra treatment because the gitlab-runner doesn't check out the full history
        - git push github HEAD:master --tags
