variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_flext:
  stage: test
  script:
    - ./bootstrap.sh
    - ./configure --with-sdkdir=$HOME/pure-data/src --enable-cmem
    - make

test_flext:
  stage: test
  dependencies:
    - build_flext
  script:
    - ( for f in $CI_PROJECT_DIR/tutorial/{1_simple1,2_adv2,3_*,4_*,5_*,7_*}/*.pd_*; do 
        p="${f%/*}"; ex="${f##*/}"; n="${ex%%.*}";
        if ! pd -noprefs -open $CI_PROJECT_DIR/tutorial/pd/test.pd -nort -noprefs -noaudio -nomidi -nogui -path "$p" -send "r obj $n" -send "r del 100" -send "r quit 1000" &> $CI_PROJECT_DIR/output.txt || grep error "$CI_PROJECT_DIR/output.txt"; then
          false
          exit # exit (subshell)
        fi
      done )

push_github:
    stage: deploy
    script:
        - git remote add github https://$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$CI_PROJECT_NAME.git || true
        # we need some extra treatment because the gitlab-runner doesn't check out the full history
        - git push github HEAD:master --tags
